data:extend(
{
 {
  type = "item",
    name = "bentonit",
    icon = "__vintorio__/graphics/bentonit.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "p-point",
    icon = "__vintorio__/graphics/p-point.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "cork-bark",
    icon = "__vintorio__/graphics/cork-bark.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "wine-cork",
    icon = "__vintorio__/graphics/wine-cork.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "wine-label",
    icon = "__vintorio__/graphics/wine-label.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "white-wine-bottle-70",
    icon = "__vintorio__/graphics/white-wine-bottle.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "white-wine-bottle-80",
    icon = "__vintorio__/graphics/white-wine-bottle.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "white-wine-bottle-90",
    icon = "__vintorio__/graphics/white-wine-bottle.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "white-wine-bottle-100",
    icon = "__vintorio__/graphics/white-wine-bottle.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "white-wine-bottle-110",
    icon = "__vintorio__/graphics/white-wine-bottle.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "gelatine",
    icon = "__vintorio__/graphics/gelatine.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
   {
  type = "item",
    name = "wine-yeast",
    icon = "__vintorio__/graphics/wine-yeast.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
   {
  type = "item",
    name = "solid-lees",
    icon = "__vintorio__/graphics/solid-lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
 type = "fluid",
    name = "rectified-grape-must",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.3, g=1.0, b=0.6},
    flow_color = {r=0.3, g=1.0, b=0.6},
    icon = "__vintorio__/graphics/rectified-grape-must.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
 
  {
  type = "item",
    name = "phosphonic-acid",
    icon = "__vintorio__/graphics/phosphonic-acid.png",
    icon_size = 32,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
 type = "fluid",
    name = "plant-protection-fluid",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.3, g=1.0, b=0.6},
    flow_color = {r=0.3, g=1.0, b=0.6},
    icon = "__vintorio__/graphics/plant-protection-product.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
{
 type = "fluid",
    name = "liquid-phosphorus-trichloride",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.3, g=1.0, b=0.6},
    flow_color = {r=0.3, g=1.0, b=0.6},
    icon = "__vintorio__/graphics/liquid-phosphorus-trichloride.png",
    icon_size = 32,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
 

    {
  type = "item",
    name = "grapes-70",
    icon = "__vintorio__/graphics/grapes-white.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "grapes-80",
    icon = "__vintorio__/graphics/grapes-white.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },  {
  type = "item",
    name = "grapes-90",
    icon = "__vintorio__/graphics/grapes-white.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },  {
  type = "item",
    name = "grapes-100",
    icon = "__vintorio__/graphics/grapes-white.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },  {
  type = "item",
    name = "grapes-110",
    icon = "__vintorio__/graphics/grapes-white.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
 {
  type = "item",
    name = "crated-grapes-70",
    icon = "__vintorio__/graphics/crated-grapes-white.png",
    icon_size = 32,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
   name = "crated-grapes-80",
    icon = "__vintorio__/graphics/crated-grapes-white.png",
    icon_size = 32,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },  {
  type = "item",
  name = "crated-grapes-90",
    icon = "__vintorio__/graphics/crated-grapes-white.png",
    icon_size = 32,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },  {
  type = "item",
    name = "crated-grapes-100",
    icon = "__vintorio__/graphics/crated-grapes-white.png",
    icon_size = 32,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },  {
  type = "item",
    name = "crated-grapes-110",
    icon = "__vintorio__/graphics/crated-grapes-white.png",
    icon_size = 32,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
 {
 type = "fluid",
    name = "mashed-grapes-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-2.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
 {
 type = "fluid",
    name = "mashed-grapes-80",
   heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-2.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
 {
  type = "fluid",
    name = "mashed-grapes-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-2.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
 {
 type = "fluid",
    name = "mashed-grapes-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-2.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
 {
 type = "fluid",
    name = "mashed-grapes-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-2.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "sulfurized-mashed-grapes-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-3.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "sulfurized-mashed-grapes-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-3.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "sulfurized-mashed-grapes-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-3.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "sulfurized-mashed-grapes-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-3.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "sulfurized-mashed-grapes-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-3.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "grape-must-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-4.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "grape-must-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-4.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "grape-must-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-4.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "grape-must-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-4.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "grape-must-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-4.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "cleared-grape-must-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-5.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "cleared-grape-must-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-5.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "cleared-grape-must-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-5.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "cleared-grape-must-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-5.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "cleared-grape-must-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-5.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
  type = "item",
    name = "grapes-pulp",
    icon = "__vintorio__/graphics/grapes-pulp.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  {
  type = "item",
    name = "empty-bottle",
    icon = "__vintorio__/graphics/empty-bottle.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  
  {
 type = "fluid",
    name = "treated-cleared-grape-must-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-6.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-grape-must-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-6.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-b[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-grape-must-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-6.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-c[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-grape-must-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-6.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-d[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-grape-must-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-6.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "young-wine-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-7.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "young-wine-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-7.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-b[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  {
 type = "fluid",
    name = "young-wine-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-7.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-c[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  {
 type = "fluid",
    name = "young-wine-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-7.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-d[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  {
 type = "fluid",
    name = "young-wine-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-7.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "cleared-young-wine-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-8.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "cleared-young-wine-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-8.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "cleared-young-wine-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-8.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "cleared-young-wine-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-8.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "cleared-young-wine-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-8.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-young-wine-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-9.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-young-wine-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-9.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-young-wine-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-9.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-young-wine-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-9.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-young-wine-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-9.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
    {
 type = "fluid",
    name = "wine-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-10.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "wine-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-10.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "wine-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-10.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "wine-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-10.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "wine-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-10.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  
  
  
  {
 type = "fluid",
    name = "wine-yeast-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "wine-yeast-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "wine-yeast-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "wine-yeast-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "wine-yeast-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  
  
  
  
  
  
   {
 type = "fluid",
    name = "grape-must-lees-70",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "grape-must-lees-80",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "grape-must-lees-90",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "grape-must-lees-100",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "grape-must-lees-110",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  --chaptalisation
  {
 type = "fluid",
    name = "grape-must-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-4.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "cleared-grape-must-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-5.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-grape-must-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-6.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "young-wine-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-7.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  
  {
 type = "fluid",
    name = "grape-must-lees-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-a[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "cleared-young-wine-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-8.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "wine-yeast-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/lees.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
 type = "fluid",
    name = "treated-cleared-young-wine-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-9.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
   {
 type = "fluid",
    name = "wine-70-c",
    heat_capacity = "0.1KJ",
    default_temperature = 25,
    max_temperature = 100,
    base_color = {r=0.59, g=0.56, b=0.27},
    flow_color = {r=0.59, g=0.56, b=0.27},
    icon = "__vintorio__/graphics/grapes-white-10.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "x[fluid]-e[water]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
  type = "item",
    name = "white-wine-bottle-70-c",
    icon = "__vintorio__/graphics/white-wine-bottle.png",
    icon_size = 64,
    --flags = {"goes-to-main-inventory"},
    subgroup = "vinification",
    order = "a[activated-charcoal]",
    stack_size = 50
  },
  
  
  
  }
  )